// Auto-generated by scripts/build-blog.mjs. Do not edit manually.
export const POSTS = [
  {
    title: "Understanding Lorem Ipsum",
    url: "/blog/1-lorem-ipsum",
    author: "Nikos Katsikanis",
    date: "2025-01-01T00:00:00.000Z",
  },
  {
    title: "Dolor Sit Amet Explained",
    url: "/blog/2-dolor-sit",
    author: "Nikos Katsikanis",
    date: "2025-01-02T00:00:00.000Z",
  },
  {
    title: "Consectetur Adipiscing Tips",
    url: "/blog/3-consectetur",
    author: "Nikos Katsikanis",
    date: "2025-01-03T00:00:00.000Z",
  },
  {
    title: "Sed Do Eiusmod Insights",
    url: "/blog/4-adipiscing",
    author: "Nikos Katsikanis",
    date: "2025-01-04T00:00:00.000Z",
  },
  {
    title: "Vanilla JS Patterns Release News",
    url: "/blog/5-breaking-news",
    author: "Nikos Katsikanis",
    date: "2025-05-01T00:00:00.000Z",
  }
];
